spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/bookservice?characterEncoding=UTF-8&serverTimezone=UTC #serverTimezone=Asia/Seoul
    username: root
    password: Abcd123@

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
    #open-in-view: true
    #generate-ddl: true
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace


server:
  port: 8087